# device_flash_esp8266.yaml
esphome:
  name: led_device_esp8266
esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret API

ota:
  password: !secret OTA

logger:

# Подключаем основной конфиг из GitHub
packages:
  common:
    url: https://raw.githubusercontent.com/zad1ak/ha/refs/heads/main/esphome/backlight/esphome/main/esphome_main_config.yaml
